### ISSUE TITLE
Needs compatibility with the latest Jira 8.21

### ISSUE THREAD

**Issue by AlexeyBaranovsky** [AndreyVMarkelov/unique-regex-custom-field#13]
Hello,
Thank you very much for your great plugin, it's very helpful for us.
We've been using it for several years but now we are planning to upgrade our Jira server up to the latest Jira version 8.21
Could you please update the plugin to be compatible with the latest Jira 8.21(8.20)?
Thank you in advance.
Alexey

**Comment by AndreyVMarkelov** [comment]
Done
