### ISSUE TITLE
Plugin no longer configurable in Jira 9.x+

### ISSUE THREAD

**Issue by 726a67** [AndreyVMarkelov/unique-regex-custom-field#16]
@AndreyVMarkelov, are there any plans to update this plugin to work in Jira 9.x products? When deployed in these environments, the plugin's configuration can no longer be accessed or modified.

Existing custom fields seem to retain their core functionality, but obviously this won't work for users who either need to modify their fields or deploy new ones.

**Comment by AndreyVMarkelov** [comment]
Fixed
