### ISSUE TITLE
Migrating jira with Unique Regex Custom Field version 1.2.20-jira7

### ISSUE THREAD

**Issue by alexsandro-itmethods** [AndreyVMarkelov/unique-regex-custom-field#3]
Hi,

I am supporting one of our customers on migration their Jira Software 7.13.1  DC installation to a different environment on AWS utilizing the XML import/export. 

Can you please confirm if this process will move over the app data?  if not, is there an alternative approach to ensure that any data/configuration created in the source instance will move over to the target instance.

Thanks,

**Comment by alexsandro-itmethods** [comment]
Hi,

I'd like to know if there is any update on this request.

Thanks,

Alexsandro

**Comment by AndreyVMarkelov** [comment]
@alexsandro-itmethods You can do it. All with the plugin standart jira api.
