### ISSUE TITLE
Data Center 

### ISSUE THREAD

**Issue by Jokabu2** [AndreyVMarkelov/unique-regex-custom-field#6]
Hello everyone,

is there a Datacenter version in planing? We would like to use this App in our Datacenter environment but we only install DataCenter Apps on the instance. 

Best regards
Tomas

**Comment by AndreyVMarkelov** [comment]
@Jokabu2 I am in the progress. Actually you can install build to DC and it will work. 
to be on market need to provide some tests which takes times because I dont have required instances

**Comment by AndreyVMarkelov** [comment]
Done
